
name: release_to_master

on: [workflow_dispatch]

env:
  CI: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ActionwareIO/branch-push-action@action
        with:
          branch: main
          files: |
            ./templates/front-app/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}