
name: release_to_master

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target branch'
        required: true
        default: 'main'

env:
  CI: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ActionwareIO/branch-push-action@action
        with:
          branch: ${{github.event.inputs.target-branch}}
          files: |
            ./templates/front-app/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}